language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install coveralls

script: 
  - coverage run info.py
  
after_success:
  COVERALLS_REPO_TOKENYcXkK6dd96zem25nOrsOUeyc4ozpzI0HF =coveralls
